apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  labels:
    app: simple-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app
        image: docker.io/thecrazyrussian/simple-app:3
        ports:
        - containerPort: 80
        env:
          - name: MY_POD_NODE
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName